language: python

cache: pip

python:
  - "{{ cookiecutter.python_version }}"

install:
  - pip install poetry codecov
  - poetry install

script:
  - make lint test

after_success:
  - codecov

before_deploy:
  - make build docs

deploy:
  - provider: script
    script: poetry publish --no-interaction --username=$PYPI_USERNAME --password=$PYPI_PASSWORD
    skip_cleanup: true
    skip_existing: true
    on:
      branch: {{ cookiecutter.branch }}
      tags: true

  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local-dir: site
    on:
      branch: {{ cookiecutter.branch }}
